DROP TABLE IF EXISTS app_user_role;
DROP TABLE IF EXISTS todo;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS role;

-- --------------------------------------------------
-- ROLE
-- --------------------------------------------------
CREATE TABLE role (
                      id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      label VARCHAR(255)
);

-- --------------------------------------------------
-- APP_USER
-- --------------------------------------------------
CREATE TABLE app_user (
                          id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email    VARCHAR(255),
                          name     VARCHAR(255),
                          password VARCHAR(255)
);

-- --------------------------------------------------
-- TODO
-- --------------------------------------------------
CREATE TABLE todo (
                      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      created_date DATE,
                      description  VARCHAR(255),
                      title        VARCHAR(255),
                      status       VARCHAR(255)
                          CHECK (status IN ('TODO','IN_PROGRESS','DONE')),
                      user_id      BIGINT,
                      CONSTRAINT fk_todo_user FOREIGN KEY (user_id)
                          REFERENCES app_user(id)
);

-- --------------------------------------------------
-- APP_USER_ROLE (join table)
-- --------------------------------------------------
CREATE TABLE app_user_role (
                               users_id BIGINT NOT NULL,
                               role_id  BIGINT NOT NULL,
                               CONSTRAINT fk_usr_role_user FOREIGN KEY (users_id) REFERENCES app_user(id),
                               CONSTRAINT fk_usr_role_role FOREIGN KEY (role_id)  REFERENCES role(id),
                               PRIMARY KEY (users_id, role_id)
);
